const COMMAND_ALGO_DFS = "dfs";
const INITIAL_TIME_MULTIPLIER_VISITED_NODES = 10;
const INITIAL_TIME_MULTIPLIER_END_NODE_PATH = 5;

export default
{
    COMMAND_ALGO_DFS,
    INITIAL_TIME_MULTIPLIER_VISITED_NODES,
    INITIAL_TIME_MULTIPLIER_END_NODE_PATH
}