const COMMAND_RESET_GRID = "reset";
const COMMAND_ALGO_DFS = "dfs";
const COMMAND_ALGO_BFS = "bfs";

const INITIAL_TIME_MULTIPLIER_VISITED_NODES = 10;
const INITIAL_TIME_MULTIPLIER_END_NODE_PATH = 5;

export default
{
    COMMAND_RESET_GRID,
    COMMAND_ALGO_DFS,
    COMMAND_ALGO_BFS,
    INITIAL_TIME_MULTIPLIER_VISITED_NODES,
    INITIAL_TIME_MULTIPLIER_END_NODE_PATH
}